# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: bitnami/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=secret
      - MONGODB_USERNAME=backend
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=troycstyle

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret